import { Inter } from 'next/font/google'
import './globals.css'
import { NavBar } from '@/components/NavBar'
import getCurrentUser from '@/actions/getCurrentUser'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/service/nextAuth'
import Script from 'next/script'
import { ToastContainer } from 'react-toastify'
import { ToastProvider } from '@/providers/ToastProvider'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const currentUser = await getCurrentUser()
  const session = await getServerSession(authOptions)

  console.log('SESSION : ', session)
  console.log('CURRENT USER : ', currentUser)

  return (
    <html lang='en'>
      {/* <Script
        type='text/javascript'
        src='//dapi.kakao.com/v2/maps/sdk.js?appkey=d77f148e757e708a19a199e532a4b16a'
      /> */}
      <body className={inter.className}>
        <NavBar currentUser={session?.user!} />
        <ToastProvider />
        <div>
          {/* <SwrProdvider>{children}</SwrProdvider> */}

          {children}
        </div>
      </body>
    </html>
  )
}
