import { Inter } from 'next/font/google'
import './globals.css'
import { NavBar } from '@/components/NavBar'
import getCurrentUser from '@/actions/getCurrentUser'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/service/nextAuth'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const currentUser = await getCurrentUser()
  const session = await getServerSession(authOptions)

  return (
    <html lang='en'>
      <body className={inter.className}>
        <NavBar currentUser={session?.user as typeof currentUser} />
        <div>{children}</div>
      </body>
    </html>
  )
}
